# Name of the action
name: Automatic Release

# Event to run on
on:
  release:
    types: [created]

permissions:
  contents: write

# Jobs that will execute
jobs:
  release:
    name: Setup Environment, Build JAR and Release Project
    runs-on: ubuntu-latest
    steps:
      - name: Automatic Release
        uses: Fulminazzo/java-automatic-release@v1
        with:
          java-version: 17
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY_NAME: ${{ github.event.repository.name }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}